[package]
name = "panic-to-result-macro"
version = "0.1.0"
edition = "2024"

[dependencies]
proc-macro2 = "1.0.70"
quote = "1.0.40"
syn = { version = "2.0.104", features = ["full", "extra-traits"] }


[lib]
proc-macro = true
