[package]
name = "builder-usage"
version = "0.1.0"
edition = "2024"

[dependencies]
builder-macro = { path = "../builder-macro" }

[dev-dependencies]
trybuild = "1.0.106"

# [[test]]
# name = "usage-tests"
